services:
    db:
      container_name: ps-mysql
      image: mysql
      volumes:
          - $PWD/data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: 12345678
          MYSQL_DATABASE: ps
          MYSQL_USER: ps
          MYSQL_PASSWORD: ps
      ports:
        - "3306:3306"
      networks:
        - my_net
    
    ps:
      container_name: ps-web
      volumes:
          - $PWD/html:/var/www/html
      depends_on:
          - db
      image: bitnami/prestashop
      ports:
        - "80:8080"
      environment:
          PRESTASHOP_DATABASE_HOST: db
          PRESTASHOP_DATABASE_PORT_NUMBER: 3306
          PRESTASHOP_DATABASE_USER: ps
          PRESTASHOP_DATABASE_PASSWORD: ps
          PRESTASHOP_DATABASE_NAME: ps
      networks:
          - my_net
networks:
  my_net:
