services:
  web:
    container_name: nginx2
    ports:
      - "8081:80"
    image: nginx
    networks:
      - network-test
  web2:
    container_name: apache
    ports:
      - "8082:80"
    image: httpd
    networks:
      - network-test
networks:
  network-test:
