apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  #superman@google.com
  PG_USER_EMAIL: c3VwZXJtYW5AZ29vZ2xlLmNvbQ==
  #EstoEsUnPasswordSecreto
  PG_USER_PASSWORD: RXN0b0VzVW5QYXNzd29yZFNlY3JldG8=